### ISSUE TITLE
Syntax error while instalation

### ISSUE THREAD

**Issue by xrombik** [NJDFan/indexedproperty#1]
Trying to install `indexedproperty` with `setup.py` leads to the following error:
```
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from indexedproperty import __version__
  File "/mnt/sda2/My Documents/Visual Studio 2005/Projects/indexedproperty/indexedproperty/__init__.py", line 241
    def __init__(self, getter=None, name=None, doc=None, *, tdict=None, **kwargs):
```
Steps to recreate an error
```
$git clone https://github.com/NJDFan/indexedproperty.git
$cd indexedproperty
$python2.7 setup.py build
```

**Comment by NJDFan** [comment]
What version of Python are you running? That line has keyword-only
arguments, which only become valid in Python 3.

**Comment by xrombik** [comment]
I'm using  python2.7. Is my solution compatible with python3? https://github.com/NJDFan/indexedproperty/pull/2
